# Generated by Django 5.1.7 on 2025-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_photo_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("photographer", "Photographer"), ("client", "Client")],
                default="photographer",
                max_length=20,
            ),
        ),
    ]
