# Generated by Django 5.1.7 on 2025-04-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_profile_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
    ]
