# Generated by Django 5.1.7 on 2025-04-01 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_profile_user_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_albums",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
